### ISSUE TITLE
Add an initial cut of "Transaction Details" screen

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#10]
> [!IMPORTANT]
> **If you would like to work on this, please comment and we will assign you to the issue.**

---

Consumers cannot currently view transaction details on the **Transactions** tab.

Would be nice to have a screen for transaction details with a similar layout to the block details screen (see below).

<img width="400" alt="Screenshot 2023-08-28 at 7 10 48 am" src="https://github.com/paradigmxyz/rivet/assets/7336481/0632a8b5-302a-4e66-92b8-2104275a0307">

Transaction details screen should prettify data from the transaction (and receipt for mined transactions), similar to Etherscan.

**Suggested Implementation**

1. Add a `TransactionDetails` component to `src/screens/`,
1. Add a `transaction-details` route to `src/index.tsx` with the newly added component,
1. Add the following Hooks
  a. `useTransaction` (implements [viem's `getTransaction`](https://viem.sh/docs/actions/public/getTransaction.html))
  b.  `useTransactionReceipt` (implements [viem's `getTransactionReceipt`](https://viem.sh/docs/actions/public/getTransactionReceipt.html))
1. Improvize some pretty UI – we can polish later.
1. **Bonus point:** add the ability to drop a pending transaction with [viem's `dropTransaction`](https://viem.sh/docs/actions/test/dropTransaction.html).

**Comment by therealharpaljadeja** [comment]
I want to take this up!

**Comment by therealharpaljadeja** [comment]
Do we want the sudden load or showing loading state (basically "pending" in place of values)?

https://github.com/paradigmxyz/rivet/assets/38040789/dd5d1c8a-3d38-4f62-81e4-2b2798827c6a

**Comment by tmm** [comment]
> Can't get `Input Data` to be wrapped 😅, might need to change the `design-system` components

You can do this if you want or create a new issue so that we can track it.

> Do we want the sudden load or showing loading state (basically "pending" in place of values)?

Think the sudden load is fine for now. We can improve loading states across Rivet in its own task.

**Comment by therealharpaljadeja** [comment]
How do I resolve this, when making commits? 😅

I can change the order of imports but when I save it goes back to how it was... I have rome extension in vscode

<img width="748" alt="image" src="https://github.com/paradigmxyz/rivet/assets/38040789/4e394b0e-8b03-4008-b437-4d4f677608d9">

**Comment by ditto-eth** [comment]
> Can't get Input Data to be wrapped 😅, might need to change the design-system components

was thinking about a similar [issue](https://github.com/paradigmxyz/rivet/issues/15#issuecomment-1695953037) (makes sense if relating to a number/value that has no spaces), looks like it's related to how wrapping and how text is broken up - adding `overflow-wrap: break-world` (or `anywhere`) seems to be one idea that could be added somewhere.

and relating to the formatting, maybe the contributing should mention you should download rome extension too

**Comment by therealharpaljadeja** [comment]
yeah `organizeImports` is causing the issue, but it's weird that it formats the imports in the code incorrectly and then the same thing throws an error when committing 😂 

I don't want to change any config, since the authors might want me to keep it as is, no idea though...

**Comment by ditto-eth** [comment]
Oh is there a bug with the automatic sorting? it is an experimental config option, so maybe it needs to be disabled if I'm understanding you correctly

**Comment by tmm** [comment]
You should be able to run `pnpm lint:fix` (if that doesn't work `pnpm lint --apply-unsafe`) to fix issues with files.
