### ISSUE TITLE
Expand truncated addresses & hashes

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#11]
> [!IMPORTANT]
> **If you would like to work on this, please comment and we will assign you to the issue.**

---

Hovering over truncated addresses & hashes should show a tooltip with the expanded data.

<img width="355" alt="Screenshot 2023-08-28 at 7 18 16 am" src="https://github.com/paradigmxyz/rivet/assets/7336481/84c5c5ab-9b06-4b3d-9b12-6bca275c0ebe">

**Suggested Implementation:**
1. Add a `Tooltip` component to `src/components/` which utilizes [Radix's `Tooltip`](https://www.radix-ui.com/primitives/docs/components/tooltip) – improvize on the design, we can polish later.
2. Utilize the new `Tooltip` component for truncated text.

**Comment by zencephalon** [comment]
I'll take this!

**Comment by jxom** [comment]
tytytyty
