### ISSUE TITLE
Display list of Sessions

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#12]
> [!IMPORTANT]
> **If you would like to work on this, please comment and we will assign you to the issue.**

---

When you click on the Dapp Connection component (see below),

<img width="403" alt="Screenshot 2023-08-28 at 7 21 14 am" src="https://github.com/paradigmxyz/rivet/assets/7336481/3a8ef8a8-e2a8-4268-a22b-6933425d12a0">

There is currently a placeholder "TODO" text under "Sessions".

It would be nice to show a list of Dapp Sessions which are active here. It can just be a simple list of hostnames for now, and we can iterate on other things later (authorized chain ids, etc).

**Suggested Implementation:**
1. Add a `getSessions` action to `src/zustand/sessions.ts`, then,
2. Extract the sessions with the `useSessionStore` Hook,
3. Improvize a pretty UI (we can iterate on polish after)

**Comment by datadanne** [comment]
Hey! I would like to work on this

**Comment by jxom** [comment]
sure!
