### ISSUE TITLE
Incorrect automine label

### ISSUE THREAD

**Issue by naps62** [paradigmxyz/rivet#18]
Am I getting this wrong or the "automine" label here is reversed? if I enable automine it shows "on demand". should be the other way around, right?

![image](https://github.com/paradigmxyz/rivet/assets/283819/ce6156e5-45d6-44bb-a96c-5ed3427547d0)

**Comment by jxom** [comment]
That button is to turn off automining.

This whole screen needs a bit of polishing (still prototype). Will add another issue for this!

**Comment by naps62** [comment]
that doesn't seem to be current behaviour.
When I do have automine (as in, I see the block number updating), this is the UI state:

![image](https://github.com/paradigmxyz/rivet/assets/283819/e2ff8beb-ea05-4989-bb77-be931d41c2be)

Clicking "On" makes it stop, reaching the state on the 1st screenshot. button says "Off", which seems correct, but "Mining Status" seems wrong

**Comment by jxom** [comment]
That's **interval mining** in your screenshot, no?

**Comment by naps62** [comment]
hmm sorry. I guess it's my jet lag still kicking in 😅 

I was reading automining and registering it as being interval (the name kind of allows for that interpretation I guess)
