### ISSUE TITLE
Bug: Rivet makes Google Docs/Sheets/Slides... has loading issue

### ISSUE THREAD

**Issue by piavgh** [paradigmxyz/rivet#22]
**Describe the bug**
After installing Rivet (latest version) via instructions here https://github.com/paradigmxyz/rivet#5-installing-the-web-extension, my Google Docs/Sheets/Slides... pages have an loading issue (check the screenshot below)
I tried to disable Rivet and it works. I can reproduce this behavior every time

Commit of Rivet: `fe16c28 fix: add guard to infinite block fetching`

**To Reproduce**
1. Install Rivet extension
2. Go to https://docs.google.com/
3. See error

**Expected behavior**
Enable Rivet should not interfere with Google Docs/Sheets/Slides...

**Screenshots**
![Screenshot 2023-08-29 at 4 13 32 PM](https://github.com/paradigmxyz/rivet/assets/4060207/8eeac515-fcf8-429a-993a-dd939549dd18)

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.5.1
 - Browser: Chome
 - Version: 116.0.5845.110 (Official Build) (x86_64)

**Additional context**

**Comment by therealharpaljadeja** [comment]
Can't use google accordion wtf did this extension do 😂

<img width="1215" alt="image" src="https://github.com/paradigmxyz/rivet/assets/38040789/d9e71bf9-cde2-47c4-9984-de6e027948b9">

**Comment by JosepBove** [comment]
It also breaks discourse (Most of the governance forums) I am looking into this

**Comment by jxom** [comment]
Ah yes. This is a known issue that only occurs on a development build. Happy for someone to take a closer look!

**Comment by JosepBove** [comment]
It's probably an error when trying to load the JS dynamically and asynchronously on the index instead of to bundling it. Anyone does know a workaround on this?

**Comment by appleseed-iii** [comment]
breaks etherscan too fyi

**Comment by jxom** [comment]
Fixed via https://github.com/paradigmxyz/rivet/commit/7480d03c1927c9184017e6b5bd423799e782443a.

May the googles, accordions, etherscans, etc be with you.

**Comment by piavgh** [comment]
@jxom : thanks, the fix works on my end 👍
