### ISSUE TITLE
Rome has ceased development 

### ISSUE THREAD

**Issue by sambacha** [paradigmxyz/rivet#31]
RIP: https://twitter.com/JNYBGR/status/1696753075678056591

U can see https://biomejs.dev/blog/annoucing-biome

**Comment by tmm** [comment]
Very easy to migrate over if anyone wants to pick this up.

- [Rome to Biome migration guide](https://biomejs.dev/blog/annoucing-biome#i-still-use-the-rome-package-what-should-i-do)

**Comment by therealharpaljadeja** [comment]
@tmm assign me
