### ISSUE TITLE
Bug: Did not get redirect after setting up local testnet

### ISSUE THREAD

**Issue by 0xlxy** [paradigmxyz/rivet#34]
**Describe the bug**
I was following the instructions to setup the wallet. On the Setup `Run Anvil` page, after running the local chain
```
anvil \
--chain-id 1 \
--fork-url https://cloudflare-eth.com
``` 
I'm suppose to get redirect to the next step. However no redirect happened while both the rivet wallet (`http://localhost:5173/`) and the local testnet (`127.0.0.1:8545`) are running locally.

**To Reproduce**
1. `pnpm dev` to start the local rivet wallet
2. upload `dist/dev` folder to the chrome extension
3. right click the rivet and click "Open Wallet in a New Tab"
4. following the Set Up procedures until 
<img width="569" alt="Screenshot 2023-09-01 at 2 25 02 PM" src="https://github.com/paradigmxyz/rivet/assets/72717104/7520b05c-a00d-4e3e-a290-a0d37c324792">

5. start the local testnet and wait for the redirect

**Expected behavior**
"When Rivet detects the Anvil instance is running, we will redirect you."

**Screenshots**
<img width="800" alt="image" src="https://github.com/paradigmxyz/rivet/assets/72717104/7d7b8cf3-3aa6-488b-8e11-80c5e6487dbd">
<img width="673" alt="image" src="https://github.com/paradigmxyz/rivet/assets/72717104/df11f86b-4e56-4afb-b545-422743c4dce9">
<img width="541" alt="image" src="https://github.com/paradigmxyz/rivet/assets/72717104/3efb6cdf-c9d2-4ca8-857a-2f459ebc94c0">

**Desktop (please complete the following information):**
 - OS: macOS Ventura Version 13.5
 - Browser: Chrome Version 113.0.5672.92 (Official Build) (arm64)

**Comment by jxom** [comment]
Can you try again? Should be fixed.
