### ISSUE TITLE
Feature: Polish loading states

### ISSUE THREAD

**Issue by AdamSchinzel** [paradigmxyz/rivet#4]
> [!IMPORTANT]
> **If you would like to work on this, please comment and we will assign you to the issue.**

---

**Describe the bug**
There are some `async` operations that are handled by a button but there is no loading/disabled state in design system for button right now so this could be handled.

**To Reproduce**
1. Try to import account by typing ENS handle (but probably more places)

**Expected behavior**
When operation handled by a button is `async` it will show some spinner instead of text and disable the button.

**Comment by snkashis** [comment]
Do you think this might be partially related to the huge amount of errors I get very soon after loading the test dapp?

<img width="1539" alt="Screenshot 2023-08-26 at 8 43 27 PM" src="https://github.com/paradigmxyz/rivet/assets/361323/45479783-8800-4eb5-b24b-3c9dcc0d451e">

**Comment by jxom** [comment]
Happy for someone to add a `loading` prop or something to the design system `Button`. We already have a [spinner SVG](https://github.com/paradigmxyz/rivet/blob/main/src/components/svgs/Spinner.tsx) you can reuse.

**Comment by jxom** [comment]
@snkashis – Fixed this at https://github.com/paradigmxyz/rivet/commit/9dcc83aa9b0b170c0e12d644109a47a44ea6609a! Thanks for flagging.

**Comment by AdamSchinzel** [comment]
I think the whole UX for loading state could be improved:

1. For button loading we can use spinner
1. For UI loading we can come up with loading skeleton design

LMK what you think!

**Comment by jxom** [comment]
Yes, I agree that loading state can definitely be improved. It's pretty much non-existent. 

Happy for those decisions, would you like to work on this?

**Comment by AdamSchinzel** [comment]
I see that you started adding also other issue, maybe it would be great to tag them with a priority badge.

My OSS contribution time a is limited because of work at @trezor (which is open source but you know...).

So just asking from what issue would Revit benefit the most ATM?

**Comment by AdamSchinzel** [comment]
> Yes, I agree that loading state can definitely be improved. It's pretty much non-existent.
> 
> Happy for those decisions, would you like to work on this?

Would love to but I will be busy this week, if no one is assigned on this on Sunday I can take it

**Comment by sigmachirality** [comment]
I'd be down to take a look at this one!
