### ISSUE TITLE
Feature: Display logs in transaction details

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#41]
### The Request

The ability to see a list of (decoded) logs for a transaction on the transaction details screen.

### Problem

Right now, we cannot see logs that were broadcast on a transaction.

### Solution

As a user, I would like to see a list of decoded logs on the transaction details screen (akin to [Etherscan's Logs tab](https://etherscan.io/tx/0xfd5699c111131bbbcd15f92512f37443bdfdbbf3bb1e1d8ceb4296547b79a186#eventlog)).

**Comment by PDiTO** [comment]
I'd like to have a stab at this for a day or two if possible.

**Comment by PDiTO** [comment]
Any thoughts on the decoding element of this. Etherscan has the benefit of contract verification to lean on. Use a library of the most common signatures? (https://www.4byte.directory/event-signatures/)
