### ISSUE TITLE
Feature: Filter transactions by account

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#44]
### The Request

The ability to see transactions scoped to an account address.

### Problem

Right now, Rivet displays every transaction across all blocks and accounts on the "Transactions" tab. There is no way to filter transactions by account address.

### Solution

As a user, I would like the ability to filter/scope transactions on the "Transactions" tab by account address.

**Comment by 0xClint** [comment]
@jxom , I just designed at UI of filter component.

I was thinking to manipulate [transactions ](https://github.com/paradigmxyz/rivet/blob/f53a9cc89746746a1c7c910f37a831c872159d38/src/screens/index.tsx#L465-L472) data while filtering data by addresses. 

![Group 10](https://github.com/paradigmxyz/rivet/assets/97947439/e088bd98-5778-4043-bf1e-a47ccad2238e)
