### ISSUE TITLE
Feature: Search for a transaction by hash

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#45]
### The Request

The ability to search for a transaction by it's hash

### Problem

Right now, there is no way to search for a transaction by it's hash.

### Solution

As a user, when I navigate to the "Transactions" tab, I would like to search for a transaction by it's hash.

**Comment by PDiTO** [comment]
I'd like to get this one in as my first open source contribution to open source.

**Comment by PDiTO** [comment]
https://github.com/paradigmxyz/rivet/pull/51
