### ISSUE TITLE
Feature: Modify transaction request data

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#46]
### The Request

The ability to modify transaction request data (fees, gas, calldata, etc) on the "Pending Request" screen.

### Problem

As a user, when I send a transaction from a Dapp, the "Pending Request" screen pops up in Rivet, but from within that screen, there is no way to modify data such as: fees per gas, gas limit, calldata, sender/receiver addresses, etc.

### Solution

As a user, from the "Pending Request" screen, I would like the ability to modify the:

- sender/receiver address
- max fee per gas/priority fee per gas
- gas limit
- nonce
- value
- calldata

**Comment by vishkrish200** [comment]
hey, I would like to work on this. 
I have two approaches in mind,
- adding a small tiny edit icon button next to each of the data points, or
- adding a hover and onClick state to the data points so that when it is clicked it can be edited like a regular <Input /> component.
either of these is doable but would like to which approach is preferred :)

**Comment by jxom** [comment]
Think the first point would be good! Let's make sure there are no layout shifts when the text turns into an input field.

@achalvs – do you have any opinions with design here?

**Comment by vishkrish200** [comment]
@jxom do i just go ahead with the edit button? to avoid text shifting we could do it as a popover?

**Comment by jxom** [comment]
@vishkrish200 – yep, we can do that for now. We may probably need a Popover component, akin to our current Tooltip component.

**Comment by vishkrish200** [comment]
yep @jxom radix-ui already has a pretty nice popover component ready.
https://www.radix-ui.com/themes/docs/components/popover

Can use this for now

**Comment by MimmyJau** [comment]
hey @jxom @vishkrish200! i noticed there hasn't been much activity on this issue recently.

mind if i take a crack at it? if you're still working on it though, no worries.

**Comment by jxom** [comment]
@MimmyJau - go for it! Mind if I assign you to the issue?

**Comment by MimmyJau** [comment]
@jxom yes please!
