### ISSUE TITLE
Feature: Toast component

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#58]
### The Request

Foundations for a Toast component in Rivet to display for info, error, etc messaging.

### Notes

Can use a library like [Sonner](https://sonner.emilkowal.ski/) or [React Hot Toast](https://github.com/timolins/react-hot-toast)

**Comment by b4s36t4** [comment]
<img width="1728" alt="Screenshot 2023-09-15 at 1 57 43 AM" src="https://github.com/paradigmxyz/rivet/assets/59088937/ea8ea5a1-44f0-4d04-bfce-d015e8bd8df7">

Demo integration (Custom toast) using `react-hot-toast`.

**Comment by jxom** [comment]
@b4s36t4 – looking good!!

**Comment by b4s36t4** [comment]
Hey, I wanted to confirm we're going to implement custom toast component or should we just use components given by react-hot-toast?

**Comment by jxom** [comment]
We can use react-hot-toast! We can customize the styling

**Comment by b4s36t4** [comment]
Any design for component design? like figma?

**Comment by b4s36t4** [comment]
@jxom friendly bump on the above question.

**Comment by jxom** [comment]
No designs yet. Just make it look nice 👨‍🎨

**Comment by mateusz-michalik** [comment]
Hey @b4s36t4, I'm picking up https://github.com/paradigmxyz/rivet/issues/59 and will use your toast component as part of it, for now will just put some placeholder in. Thanks!

**Comment by b4s36t4** [comment]
Hey @mateusz-michalik just use toast from react hot toast, that should do the trick and work.

**Comment by mateusz-michalik** [comment]
Will do, wasn't sure if you're still going to apply some styling, I'll follow up on this in https://github.com/paradigmxyz/rivet/issues/59 though
