### ISSUE TITLE
Enhancement: UI for invalid ERC20 token imports

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#59]
Depends on #58

### The Request

The ability to see feedback in the UI when a user imports an invalid ERC20 token address.

### Problem

Right now, if a user tries to import an invalid ERC20 token address into their token list, they will receive no feedback.

### Solution

As a user, I would expect to see some error messaging (in the form of a toast message) in the UI that the ERC20 token address I tried to import is invalid. 

### Notes

See [TODO](https://github.com/paradigmxyz/rivet/blob/f3e80987b8ccf1292823400bfbfbf0ec4e9176bd/src/screens/account-details.tsx#L169)

**Comment by mateusz-michalik** [comment]
Happy to pick this one up as another one to get familiar and contribute. For now I'll put the placeholder code in place for this and then integrate https://github.com/paradigmxyz/rivet/issues/58 when it's merged

**Comment by mateusz-michalik** [comment]
Here is how it's looking using [react-hot-toast](https://react-hot-toast.com/docs/toast)

![image](https://github.com/paradigmxyz/rivet/assets/2107693/50c33ba2-c9c0-41a6-9687-f5f49ee4f256)

Going to push the PR up in a moment
