### ISSUE TITLE
Enhancement: UI for failure setting ERC20 balance

### ISSUE THREAD

**Issue by jxom** [paradigmxyz/rivet#60]
Depends on #58

### The Request

The ability to see feedback in the UI when a failure occurs while a user is trying to set an ERC20 balance.

### Problem

Right now, `balanceOf` storage slot guessing can fail for some ERC20 tokens that wildly deviate from the ERC20 interface. For these tokens, when a user tries to set a balance for them, no messaging/feedback is provided.

### Solution

As a user, when I set a balance for one of my ERC20 tokens on the token list screen, I would expect to see some error messaging (in the form of a toast message) in the UI to tell me that setting a balance failed, and for the input field to become disabled.

### Notes 

See [TODO](https://github.com/paradigmxyz/rivet/blob/f3e80987b8ccf1292823400bfbfbf0ec4e9176bd/src/screens/account-details.tsx#L254)

**Comment by About7Sharks** [comment]
Is this issue still Open?
https://github.com/paradigmxyz/rivet/pull/68 Looks like this PR should have closed it?

**Comment by jxom** [comment]
There is currently no UI to display error states for setting balances yet!
