### ISSUE TITLE
The background is completely opaque

### ISSUE THREAD

**Issue by jistro** [paradigmxyz/rivet#77]
**Describe the bug**
The background is completely transparent when I use the extension

**To Reproduce**
1. Install the extension
2. Open the extension
3. See error

**Expected behavior**

The background is expected to have the corresponding design/color, however the background appears to be removed or the background color is completely opaque

**Screenshots**
![image](https://github.com/paradigmxyz/rivet/assets/22781439/4e8d13f2-f566-4c5a-954b-0819f7988f87)

**Desktop (please complete the following information):**
 - OS: GNU/Linux Distro: pop_os 22.04 LTS
 - Browser Brave
 - Version 1.58.135 Chromium: 117.0.5938.140 (Official Build) (64-bit)

**Comment by jxom** [comment]
Looks like something went wrong in our automated web store deployment. Just submitted a new version to web store. Until that's approved, feel free to manually download the extension here: https://github.com/paradigmxyz/rivet/releases/tag/v0.0.4
