### ISSUE TITLE
Wrong chain when sending a tx via Contract tab

### ISSUE THREAD

**Issue by mlgarchery** [paradigmxyz/rivet#88]
**Describe the bug**
I intereact with an anvil fork of Goerli, and sending a tx via Contract Details ends up in an `TransactionExecutionError: The current chain of the wallet (id: 5) does not match the target chain for the transaction (id: 1 – Ethereum).`

**To Reproduce**
1. In contract details add 0x4BC8E2c58C4210098D3B16b24E2a1Ec64e3bFf22, then the abi
2. Try the deposit() function for example

Read functions work

**Screenshots**
![image](https://github.com/paradigmxyz/rivet/assets/16239564/0d60f928-1cc5-439c-b7fd-3a417c18dbc8)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chromium
 - Version: on main commit cfe2005

**Comment by jxom** [comment]
Fixed in https://github.com/paradigmxyz/rivet/commit/463951419a12f52139312a0eee370ba24c677dd4.
