### ISSUE TITLE
Feature: Show disconnected network UI

### ISSUE THREAD

**Issue by AdamSchinzel** [paradigmxyz/rivet#9]
> [!IMPORTANT]
> **If you would like to work on this, please comment and we will assign you to the issue.**

---

**Describe the bug**
In order to display some data (block, mining status etc.) or perform some actions (mine block etc.) the RPC must be up. If it's not then user see blank spaces or still can perform actions without any feedback that the action was not done.

**To Reproduce**
1. Shutdown your RPC

**Expected behavior**
Fill blank spacing with some message why I don't see them and disable actions (ideally with tooltip) again saying why it's unavailable ATM.

**Comment by jxom** [comment]
Happy for someone to work on this! 

I think I nice to have an experience akin to Browser DevTools:

<img width="649" alt="Screenshot 2023-08-28 at 7 08 07 am" src="https://github.com/paradigmxyz/rivet/assets/7336481/c6fb97d1-f29d-4955-b189-ac5781dd19f6">

Maybe something like this:

![Group 1 (11)](https://github.com/paradigmxyz/rivet/assets/7336481/9e7049d6-3705-4900-a988-b6a72191ce30)

**Comment by AdamSchinzel** [comment]
Yeah I think this looks great from the picture

**Comment by Flocqst** [comment]
Hi ! I'd like to work on this one.

**Comment by 0xClint** [comment]
#35
