### ISSUE TITLE
false-positive virus detected on extension.zip from github-actions

### ISSUE THREAD

**Issue by krakovia-evm** [paradigmxyz/rivet#91]
**Describe the bug**
There's a false-positive on Chrome/Brave browser while downloading the packed extension

**To Reproduce**
Just try to any of the two latest nightly releases on Chrome/Brave browser (PC/Win11)

![image](https://github.com/paradigmxyz/rivet/assets/90364822/9fefad10-9fc2-4966-b4f5-d3b55b305e6c)

**Comment by jxom** [comment]
Unsure what would cause this. Best to ignore it.
